[project]
name = "sample-service1"
version = "0.1.0"
description = "Example service consuming sample-lib1 with telemetry enabled"
requires-python = ">=3.10"

dependencies = [
    "toran-pytelemetry",
    "toran-sample-lib1",

    # Exporter choice lives HERE
    "opentelemetry-exporter-otlp>=1.25.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

